ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
}

db {
    jdbcUrl  = "jdbc:postgresql://localhost:5432/flashcards"
    jdbcUrl  = ${?DB_JDBC_URL}
    user     = "flashcards"
    user     = ${?DB_USER}
    password = "flashcards"
    password = ${?DB_PASSWORD}
    maxPoolSize = 5
    maxPoolSize = ${?DB_MAX_POOL_SIZE}
}
